### ISSUE TITLE
Error 404 on OS terminal OSX

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb4#4]
After executing the the app i get the following and repeats every couple of minutes
Error 404: { [Error: ENOENT: no such file or directory, open '/Users/ayahni/LaserWeb4/server/../app/inform']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/ayahni/LaserWeb4/server/../app/inform' }

Ive gone from a clean install and folder, but cant find the location the error refers to. Windows install is fine for me

This does not prevent me from connecting and interacting with the board.

**Comment by lautr3k** [comment]
This is not a bug. Just your browser (plugin, app, or something else) that asks the "inform" page/ressource. As this ressource does not exist, the web server reply with an error 404. 
Try to see in your browser console from where this come from.

I will remove 404 notifications in the console, it is not useful for the user, maybe I'll add it in a log file.

**Comment by cojarbi** [comment]
With the latest commit there error doesnt show anymore
