### ISSUE TITLE
self = this?

### ISSUE THREAD

**Issue by emteeoh** [openhardwarecoza/LaserWeb4#8]
@lautr3k I'm looking at the com code, and part way through the bind_model method, you assign self=this, and then (inconsistently) use it. Is there any particular reason for using "self", or is it just a stylistic thing?

**Comment by tbfleming** [comment]
JavaScript functions, especially callbacks, often clobber ```this```. Example:

```
this.can_connect = ko.computed(function() {
                return !self.connected() && !self.wait_connection();
            });
```

```this``` within that callback doesn't point to the object, but ```self``` does.

**Comment by emteeoh** [comment]
Ah! Thanks. That explains a lot.

**Comment by lautr3k** [comment]
MEACULPA (bis); Another thing that ES6 corrects with Arrow objects.

**Comment by emteeoh** [comment]
I am *soooo* glad I asked this question! I ran into a problem that happened because of this, so I created self and it worked! It was like I debugged the problem (with your help!) before writing the code.

**Comment by tbfleming** [comment]
You might consider arrow functions for newly-written callbacks like @lautr3k alluded to; ES6 added them to replace the self workaround. Chrome supports it without having to use Babel.

**Comment by emteeoh** [comment]
Need to learn about them first! In the meantime, self got me moving forward...
